name: sklearn-example
channels:
        - defaults
        - anaconda
dependencies:
        - python==3.6
        - scikit-learn=0.21.3
        - pip==19.3.1
        - pip:
                - mlflow>=1.0
